### ISSUE TITLE
Suggestion: add one extra placeholder - money lost in total.

### ISSUE THREAD

**Issue by SenorFlamingo** [Zithium-Studios/DeluxeCoinflip#16]
It could be an interesting extra statistic to see how much money was won or lost in total by a player aside from the total profit.

**Comment by gamingjovi** [comment]
There's a profit placeholder within the GUI.

**Comment by SenorFlamingo** [comment]
> There's a profit placeholder within the GUI.

I know, but there's currently not a way of showing how much money has been won or lost in total.

**Comment by TiboOpGithub** [comment]
Would be a really nice feature!

**Comment by engeltjuuh** [comment]
I would love this feature!
